# Welcome to AsciiDocsy!
#
# This is a "default" Jekyll config file for this theme, but it is probably
# not what you want to use in production.
# Be sure to check out the README, which contextualizes this project.
# See also https://jekyllrb.com/docs/configuration/default/ for more
#  configuration options.
# NOTE: AsciiDocsy makes much heavier than typical use of the `site.` and
#  `data.` scopes in order to minimize the need to modify templates.
# NOTE: Where you see the likes of `tag::some-text[]` and `end::some-text[]`
#  in this file, these are AsciiDoc flags marking places to extract for
#  sourcing the docs for this theme itself.

title: AsciiDocsy
tagline: An AsciiDoc-ready Jekyll theme for technical documentation
deploy_url: https://asciidocsy.netlify.app # your site's URL
canonical_url: https://asciidocsy.netlify.app # URL of original content
# DO NOT CHANGE the canonical URL if you deploy a copy the AsciiDocsy site
# DO change it if you replace all the content or start from scratch
company_name: DocOps Labs

# SITEWIDE JEKYLL SETTINGS
baseurl: "" # Leave blank if your site will deploy at the root of a domain
            #  such as http://docs.yourcompany.com/
# The following paths are all relative to the project base
source: .
destination: _site
layouts_dir: _layouts
includes_dir: _includes

# Global AsciiDocsy settings
theme_dir: "" # <1> path to asset directories (css/ images/ js/ etc)
assets_url: ""
data_dir: _docs/_data
source_git: git@github.com:DocOps/asciidocsy-jekyll-theme.git # git@-formatted address
source_www: https://github.com/DocOps/asciidocsy-jekyll-theme
source_icon: fa fa-github
source_trunk_branch: main # path from repo home url to projet root
images_path: /images
subject_tickets_www: https://github.com/DocOps/asciidocsy-jekyll-theme/issues
docs_tickets_www: https://github.com/DocOps/asciidocsy-jekyll-theme/issues

# tag::asciidoctor[]
asciidoc: {}
asciidoctor:
  ext: adoc
  safe: 0
  base_dir: .
  attributes:
    imagesdir: /images
    icons: font
    source-highlighter: highlight.js
    ### paths from topic/ to root files
    topics_path: _docs/topics
    path_to_jekyll_config: _config.yml
    path_to_readme: README.adoc
    path_to_data_dir: _docs/_data
    path_to_snippets: _docs/snippets
    example-capition: ''
    experimental:
# end::asciidoctor[]

liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Default PAGE scopes for content sourced in certain paths
defaults:
  - scope:
      path: ""
    values:
      search-index: false
      style-changers: false
  - scope:
      path: pages/
    values:
      layout: page
      kind: page
      sidebar-left: true
      sidebar-right: true
  - scope:
      path: _docs/topics/
    values:
      layout: topic
      kind: topic
      sidebar-left: true
      sidebar-right: true
      search-index: true
      anchors: true
      toc: [sidebar]

# Paths to render with Jekyll that would not be rendered by default
include:
  - _docs
  - _docs/_data/terms-dict.json
  - _docs/theme-api.asciidoc

# Paths to skip that would normally be rendered
exclude:
  - .data # the root data/ dir is for data ABOUT AsciiDocsy
  - "**/README.adoc" # if we want content from READMEs, we include:: it
  - COPYRIGHT
  - LICENSE
  - _docs/snippets

# FEATURES
#
# This is AsciiDocsy's novel way of putting powerful feature configuration
#  in a convenient spot.
# What follows is just a data structure -- it is not a language.
# All functionality is coded into Liquid templates.
#
# TO DISABLE any feature or block of features, delete it or comment it out.
features:
  navigation:
    anchor-links:
      $doc:
        name: Anchor Links
        desc: Adds self-referential links to all headers of the listed types.
      show:
        list: h2,h3,h4,h5 # make empty to disable anchor links
    subject-menu:
      $doc:
        desc: Determines the source and display of the _subject_ navigation menu.
      opts:
        show_type_icons: false
    toc:
      $doc:
        name: TOC
        desc: Shows and sets the depth of the table of contents.
      show:
        text: In this topic…
        spot: "#sidebar-right"
        opts:
          header_level_depth: "h3"
    breadcrumbs:
      $doc:
        desc: Displays and designs the breadcrumb trail.
        tips:
          - Crumb paths are further defined in data/manifest.yml.
      show:
        home: Home
        opts:
          delim: ">" # defaults to "/"
  alerts:
    gdpr-message:
      # NOT YET IMPLEMENTED
      # see features.actions.gdpr-alert for more settings
      name: Cookies & Privacy
      show:
        line: Select cookies to accept.
        text: | # AsciiDoc formatting allowed
          This website stores cookies on your computer.
          These cookies keep track of how you prefer to interact with our website and customize your browsing experience. *We and our vendors do _not_ track you elsewhere on the Internet.* To find out more, see our link:/privacy[Privacy Policy].
        icon: fa fa-exclamation-circle
        form: banner
        when: load
    call-to-action:
      # NOT YET IMPLEMENTED
      show:
        text: |
          Don't leave the site without signing up for a demo or at least getting on our mailing list!
        icon: fa fa-hand-o
        form: modal
        when: exit
  actions:
    search-site:
      $doc:
        name: Search the site
        desc: Enables users to search all pages in the site, including non-topics
# tag::search-site-core[]
      show:
        text: Search non-docs PAGES…
        spot: "#nav-site"
      meta:
        index: asciidocsy-pages
# end::search-site-core[]
    search-subject:
      show:
        text: Search subject TOPICS…
        icon: fa fa-search
        spot: "#sidebar-left" # where this should appear (alt: leftside nav)
      meta:
        index: asciidocsy-topics
    versioning:
      defaults:
        topic:
          list: [theme-skin-amend,syntax-skin-amend]
        page:
          list: [theme-skin-amend,syntax-skin-amend]
      user-os-toggle: # arbitrary toggler name
        verb: toggle
        # form is inferred (buttons)
        spot: '#sidebar-right .sidebar-mid'
        show:
          text: "Your operating system:"
          icon: fa fa-laptop
        swap:
          pick: os-mac
          opts:
            - text: Windows
              slug: os-win
              icon: fa fa-windows
            - text: Linux/Unix
              slug: os-nix
              icon: fa fa-linux
            - text: MacOS
              slug: os-mac
              icon: fa fa-apple
      patch-swap-0_2:
# tag::sample-swap-patch[]
        verb: swap
        form: select
        spot: "#sidebar-right .sidebar-end"
        show:
          text: "Choose your patch version:"
          icon: fa fa-wrench
        swap:
          pick: 0.2.0
          slug: vrsn # <1>
          opts: ['0.2.0','0.2.1','0.2.2'] # <2>
# end::sample-swap-patch[]
      patch-swap-0_2-btns:
        verb: swap
        form: buttons
        spot: "#sidebar-right .sidebar-end"
        swap:
          pick: 0.2.0
          slug: vrsn # <1>
          opts: ['0.2.0','0.2.1','0.2.2','0.2.3'] # <2>
# THESE ARE JOKE DEMO VALUES
      spoof-tokens-swap:
# tag::sample-swap-spoof[]
        verb: swap
        form: select
        spot: "#sidebar-right .sidebar-end"
        show:
          text: "AsciiDocsy Edition:"
          icon: fa fa-font
        swap:
          pick: foss
          dict: # <1>
            company: DocOps.org
            company_url: https://www.docopslab.org
            theme: AsciiDocsy
          opts: # <2>
            - text: FOSS
              slug: foss
              dict:
                slogan: Free docs for everyone!
            - text: Freemium
              slug: freemium
              dict: # <3>
                theme: AsciiDocsy Premium
                company_url: https://www.docopslab.com
                slogan: Free docs until you're a big deal (then chip in).
            - text: SellOut
              slug: sellout
              dict: # <3>
                theme: ACMEDocsy
                company: AsciiDocs4Sale.com
                company_url: https://asciidocs4sale.com
                slogan: No free docs.
# end::sample-swap-spoof[]
# tag::sample-swap-piggyback[]
      user-os-swap:
        verb: swap
        form: "#user-os-toggle"
        spot: "#sidebar-right .sidebar-end"
        swap:
          opts:
            - slug: os-mac
              dict:
                your_os: Your operaing system is very classy.
                you: You appreciate good design and are willing to pay for it.
            - slug: os-nix
              dict:
                your_os: Your operating system is very... rugged.
                you: You like the illusion that you take charge of your devices.
            - slug: os-win
              dict:
                your_os: Your operating system is practical.
                you: You don't overthink things.
# end::sample-swap-piggyback[]
# / END JOKE DEMO VALUES
      theme-skin-amend:
        verb: amend
        form: select
        spot: "#sidebar-right .sidebar-end"
        show:
          text: "Theme skin:"
          icon: fa fa-paint-brush
        swap:
          data: site.data.theme.skin-styles
          pick: foundation
          # opts: >-
          #   {{site.assets_url}}/css/skins/{{value}}.css
        func:
          name: change-href
          targ: "#theme-skin"
          href: >- # defaults to $(this).val(); allows Liquid
            '{{site.assets_url}}/css/skins/' + $(this).val() + '.css'

      syntax-skin-amend:
        verb: amend
        form: select
        spot: "#sidebar-right .sidebar-end"
        show:
          text: "Code highlight skin:"
          icon: fa fa-code
        swap:
          data: site.data.theme.syntax-styles
          pick: a11y-light
        func:
          name: change-href
          targ: "#syntax-skin"
          href: >-
            '{{site.assets_url}}/css/syntax/hljs/' + $(this).val() + '.css'

      data-format-tabber: # arbitrary tabset name
        verb: tab
        swap:
          pick: data-json
          opts:
            - text: YAML Data
              slug: data-yaml
            - text: JSON Data
              slug: data-json
    topic: # order these objects as you wish them to appear
      peel: # display print-friendly version
        text: Print-friendly
        icon: fa fa-newspaper-o
        func: ""
        # role: auth0 # explicitly sets role limit
      edit:
        text: Edit this topic
        icon: fa fa-pencil-square
        # role: auth0 # explicitly sets role limit
        # fork: # overrides default forking policy
      data:
        text: Edit topic datasource
        icon: fa fa-database
        # role: auth0
        # fork: # overrides default forking policy
      make:
        text: Create a (sub)topic
        icon: fa fa-file-text-o
        # role: auth0
        # fork: # overrides default forking policy
      open-docs:
        text: Open a docs ticket
        icon: fa fa-ticket
        path: /new?labels=documentation # path to append to the tickets_www URL
        # role: auth0
        # fork: # overrides default forking policy
      open-subj:
        text: Open a product ticket
        icon: fa fa-tag
        path: /new # path to append to the tickets_www URL
        # role: auth0
    page:
      edit:
        text: Edit this page
        href:
        icon: fa fa-pencil
        # role: auth0
        # fork: # overrides default forking policy
      data:
        text: Edit page datasource
        icon: fa fa-database
        # role: auth0
        # fork: # overrides default forking policy
      make:
        text: Suggest a new page
        icon: fa fa-file-text-o
        # role: auth0
        # fork: # overrides default forking policy
    page-skin: # you probably want to remove this, cool as it is
      swap:
        # list: [] # if different from default site.styles.skins.list
        # role: auth0
    syntax-style: # you probably want to remove this, cool as it is
      swap:
        # list: [] # if different from default site.styles.syntax.list
        # role: auth0
    feedback-form:
      show:
        name: Feedback, please.
        text: Did you find this page helpful?
        icon: fa fa-clipboard
      send:
        opts:
          - slug: 'yes'
            text: 'Yes'
            echo: |
              That's great! Do let us know if you have more to say.
            icon: fa fa-trophy
          - slug: 'no'
            text: 'No'
            echo: |
              We are sorry to hear that.

              More text
            icon: frown-o
          - slug: some
            text: Partly
            echo: |
              Okay, thanks for your honesty.

              More text
            icon: fa fa-line-chart
    gdpr-alert:
    # NOT YET IMPLEMENTED
      sign:
        text: I accept.
        icon: fa fa-thumbs-up
      pick:
        text: Customize cookies.
        icon: fa fa-edit
        opts:
          # Cookie types
          - name: Essential
            slug: essential
            desc: These are cookies that are essential for the website to work correctly.
          - name: Site Preferences
            slug: preferences
            desc: These are cookies that are related to your site preferences, e.g. remembering your username, site colours, etc.
          - name: Analytics
            slug: analytics
            desc: Cookies related to site visits, browser types, etc.
          - name: Marketing
            slug: marketing
            desc: Cookies related to marketing, e.g. newsletters, social media, etc
      deny:
        # the user action is to make the message go away and eliminate cookies
        icon: fa fa-thumbs-down

# ELEMENTS
header:
  show:
    logo:
      source: /images/logo.png
      width: 50px
footer:
  show:
    logo:
      source: /images/docops-labs-logo.png
      width: 150px
    opts:
      first-col-class: offset-2 # how far to offset the link columns


# SEMANTICS
semantics:
  inline:
    role:
      term:
        show:
          icon:
            text: fa fa-info-circle
            tilt: 15
            spin: true
          spot: "#sidebar-right"

# SERVICES
services:
  analytics:
    google:
  search:
    algolia:
# tag::algolia[]
      application_id: 'SELDDHION6'
      search_only_api_key: 'b9112b0485d58729c3e7c7b64291cbd9'
# end::algolia[]

social:
  show:
    spot: footer
    sites:
      - slug: twitter
        name: Twitter
        href: https://twitter.com/_codewriting
        icon: fa fa-twitter
      - slug: slack
        name: Slack
        href: https://writethedocs.slack.com
        icon: fa fa-slack
      - slug: github
        name: GitHub
        href: https://github.com/DocOps
        icon: fa fa-github
      - slug: youtube
        name: YouTube
        href: https://www.youtube.com/channel/UCr019846MitZUEhc6apDdcQ
        icon: fa fa-youtube

# SCRIPTS
scripts:
  head:
    - slug: jquery
      href: /js/jquery-3.3.1.min.js
    - slug: popper
      href: https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js
      meta:
        integrity: sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49
    - slug: bootstrap
      href: https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js
    - slug: jquery-cookie
      href: /js/jquery.cookie.js
    - slug: algolia-instantsearch
      href: https://cdn.jsdelivr.net/npm/instantsearch.js@4.8.3/dist/instantsearch.production.min.js
      meta:
        integrity: sha256-LAGhRRdtVoD6RLo2qDQsU2mp+XVSciKRC8XPOBWmofM=
    - slug: autocomplete
      href: https://cdn.jsdelivr.net/autocomplete.js/0/autocomplete.min.js
    - slug: algoliasearch-3
      href: https://cdn.jsdelivr.net/algoliasearch/3/algoliasearch.min.js
    - slug: anchors
      href: /js/anchor.min.js
    - slug: navgoco
      href: /js/jquery.navgoco.js
    - slug: bootstrap-toc
      href: /js/bootstrap-toc.js
    - slug: highlight-js
      href: /js/highlight.pack.js
    - slug: asciidoctor
      href: /js/asciidoctor.min.js
    - slug: asciidocsy-tabber
      href: /js/tabber.js
    - slug: asciidocsy-toggler
      href: /js/toggler.js
    - slug: asciidocsy-semantics
      href: /js/semantics.js
  tail:
    - slug: asciidocsy-tail
      href: /js/tail.js

# SITE POLICIES
policies:
  gdpr:
    # NOT YET IMPLEMENTED
    # This feature will enable users to
    $doc:
      name: GDPR policies
      desc: Groups cookies by use to let users select which cookies to permit.
    types:
      - slug: essential
        desc: Just the cookie to remember these preferences.
        cookies: [cookieControlPrefs]
      - slug: preferences
        desc: Cookies to recall style and version choices made in the app.
        cookies: [syntax-style,skin-style,switcher_user-os]
      - slug: analytics
        desc: Uses cookies to anonymously report how you use the site so we can improve the experience.
        cookies: [google-analytics]
      - slug: commercial
        desc: We don't use this kind of cookie anywhere on our site.
        cookies: []
  authorizations:
    # NOT YET IMPLEMENTED
    # Arbitrary tiers for referencing in other settings.
    # Authorization is ordered from lowest (first) to highest.
    # This object demonstrates only FEATURE-level permissions for page links.
    # Restricting access to whole pages/paths based on authorizations is
    #  not yet planned.
    - code: auth0
      text: all site visitors
      policies:
        fork: togo
    - code: auth1
      text: logged-in site visitors
      keys:
        - cookie: employees
        - cookie: contractors
        - token:  staff
      policies:
        fork: stay
    - code: auth2
      text: site admins only
      keys:
        - cookie: 'admins'
      policies:
        fork: stay
    # NOTE: with a static site, we are not so much protecting the source
    #  (our Git workflow does that); we are just restricting what visitors
    #  see on the page.
  defaults:
    # auth: auth0 # who sees interactive features on the site?
                # must be one of the codes listed in policies.authorizations
                # can override individually below
    fork: upto  # can users fork the repo to contribute?
                #   none = no forking or branching
                #   stay = branch only
                #   togo = fork only
                #   upto = fork or branch, user's choice
                #   auth = set under policies.authorizations


# THEME STYLE/DESIGN SETTINGS
# tag::styles[]
styles:
  logo:
    width: 50px
  color:
    theme: "#30638e"
# end::styles[]
