# Welcome to AsciiDocsy!
#
# This is a "default" Jekyll config file for this theme, but it is probably
# not what you want to use in production.
# Be sure to check out the README, which contextualizes this project and
#  points to the official theme documentation.
#
# See also https://jekyllrb.com/docs/configuration/default/ for more
#  configuration options.
#
# Global custom properties
title: My AsciiDocsy-based Site
tagline: A site built with the AsciiDoc-ready Jekyll theme for technical documentation
deploy_url: https://docs.example.com # your site's URL
canonical_url: https://docs.example.com # URL of original content
# DO NOT CHANGE the canonical URL if you deploy a copy the AsciiDocsy site
# DO change it if you replace all the content or start from scratch
company_name: ACME Everything
source_git: git@github.com:DocOps/MY-PROJECT.git # git@-formatted address
source_www: https://github.com/example-account/MY-PROJECT

# Sitewide Jekyll settings
baseurl: "" # Leave blank if your site will deploy at the root of a domain
            #  such as http://docs.yourcompany.com/
# The following paths are all relative to the project base
source: .
destination: _site
layouts_dir: _layouts
includes_dir: _includes

# Global AsciiDocsy settings
theme_dir: assets # path to asset SOURCE directories (css/ images/ js/ etc)
assets_url: /assets # baseurl to assets (default: /assets)
data_dir: _data
source_icon: fa fa-github
source_trunk_branch: main # path from repo home url to projet root

# tag::asciidoctor[]
asciidoc: {}
asciidoctor:
  ext: adoc
  safe: 0
  base_dir: .
  attributes:
    outfilesuffix: ''
    example-capition: ''
    experimental:
    imagesdir: /images
    icons: font
    source-highlighter: highlight.js
# end::asciidoctor[]

liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Paths to render with Jekyll that would not be rendered by default
include:
  - _data/terms-dict.json

# Paths to skip that would normally be rendered
exclude:
  - "**/README.adoc" # if we want content from READMEs, we include:: it
  - COPYRIGHT
  - LICENSE
