# Welcome to AsciiDocsy!
#
# This is a "default" Jekyll config file for this theme, but it is probably
# not what you want to use in production.
# Be sure to check out the README, which contextualizes this project.
# See also https://jekyllrb.com/docs/configuration/default/ for more
#  configuration options.
# NOTE: AsciiDocsy makes much heavier than typical use of the `site.` and
#  `data.` scopes in order to minimize the need to modify templates.
# NOTE: Where you see the likes of `tag::some-text[]` and `end::some-text[]`
#  in this file, these are AsciiDoc flags marking places to extract for
#  sourcing the docs for this theme itself.

title: AsciiDocsy
tagline: An AsciiDoc-ready Jekyll theme for technical documentation
deploy_url: https://asciidocsy.netlify.app # your site's URL
canonical_url: https://asciidocsy.netlify.app # URL of original content
# DO NOT CHANGE the canonical URL if you deploy a copy the AsciiDocsy site
# DO change it if you replace all the content or start from scratch
company_name: DocOps Lab

# SITEWIDE JEKYLL SETTINGS
baseurl: "" # Leave blank if your site will deploy at the root of a domain
            #  such as http://docs.yourcompany.com/
# The following paths are all relative to the project base
source: .
destination: _site
layouts_dir: _layouts
includes_dir: _includes

# Global AsciiDocsy settings
theme_dir: "" # <1> path to asset directories (css/ images/ js/ etc)
assets_url: ""
data_dir: _docs/_data
source_git: git@github.com:DocOps/asciidocsy-jekyll-theme.git # git@-formatted address
source_www: https://github.com/DocOps/asciidocsy-jekyll-theme
source_icon: fa fa-github
source_trunk_branch: main # path from repo home url to projet root
images_path: /images
subject_tickets_www: https://github.com/DocOps/asciidocsy-jekyll-theme/issues
docs_tickets_www: https://github.com/DocOps/asciidocsy-jekyll-theme/issues

# tag::asciidoctor[]
asciidoc: {}
asciidoctor:
  ext: adoc
  safe: 0
  base_dir: .
  attributes:
    outfilesuffix: ''
    imagesdir: /images
    icons: font
    source-highlighter: highlight.js
    ### paths from topic/ to root files
    topics_path: _docs/topics
    path_to_jekyll_config: _config.yml
    path_to_readme: README.adoc
    path_to_data_dir: _docs/_data
    path_to_snippets: _docs/snippets
    example-capition: ''
    experimental:
# end::asciidoctor[]

liquid:
  error_mode: warn
  strict_filters: false
  strict_variables: false

# Default PAGE scopes for content sourced in certain paths
defaults:
  - scope:
      path: ""
    values:
      search-index: false
      style-changers: false
  - scope:
      path: pages/
    values:
      layout: page
      kind: page
      sidebar-left: true
      sidebar-right: true
  - scope:
      path: _docs/topics/
    values:
      layout: topic
      kind: topic
      sidebar-left: true
      sidebar-right: true
      search-index: true
      anchors: true
      toc: [sidebar]

# Paths to render with Jekyll that would not be rendered by default
include:
  - _docs
  - _docs/_data/terms-dict.json
  - _docs/theme-api.asciidoc

# Paths to skip that would normally be rendered
exclude:
  - .data # the root data/ dir is for data ABOUT AsciiDocsy
  - "**/README.adoc" # if we want content from READMEs, we include:: it
  - COPYRIGHT
  - LICENSE
  - _docs/snippets

# tag::algolia[]
algolia:
  application_id: 'SELDDHION6'
  search_only_api_key: 'b9112b0485d58729c3e7c7b64291cbd9'
# end::algolia[]
